package com.adisa.diningplus.network.entities

import org.json.JSONObject

class Nutrition(raw: JSONObject) {
    var servingSize: String = raw.getString("serving_size")
    var calories: Int = raw.getInt("calories")
    var totalFat: String = raw.optString("total_fat")
    var saturatedFat: String = raw.optString("saturated_fat")
    var transFat: String = raw.optString("trans_fat")
    var cholesterol: String = raw.optString("cholesterol")
    var sodium: String = raw.optString("sodium")
    var totalCarbohydrate: String = raw.optString("total_carbohydrate")
    var dietaryFiber: String = raw.optString("dietary_fiber")
    var totalSugars: String = raw.optString("total_sugars")
    var protein: String = raw.optString("protein")
    var vitaminD: String = raw.optString("vitamin_d")
    var vitaminA: String = raw.optString("vitamin_a")
    var vitaminC: String = raw.optString("vitamin_c")
    var calcium: String = raw.optString("calcium")
    var iron: String = raw.optString("iron")
    var potassium: String = raw.optString("potassium")
    var totalFatPDV: Int = raw.optInt("total_fat_pdv")
    var saturatedFatPDV: Int = raw.optInt("saturated_fat_pdv")
    var transFatPDV: Int = raw.optInt("trans_fat_pdv")
    var cholesterolPDV: Int = raw.optInt("cholesterol_pdv")
    var sodiumPDV: Int = raw.optInt("sodium_pdv")
    var totalCarbohydratePDV: Int = raw.optInt("total_carbohydrate_pdv")
    var dietaryFiberPDV: Int = raw.optInt("dietary_fiber_pdv")
    var totalSugarsPDV: Int = raw.optInt("total_sugars_pdv")
    var proteinPDV: Int = raw.optInt("protein_pdv")
    var vitaminDPDV: Int = raw.optInt("vitamin_d_pdv")
    var vitaminAPDV: Int = raw.optInt("vitamin_a_pdv")
    var vitaminCPDV: Int = raw.optInt("vitamin_c_pdv")
    var calciumPDV: Int = raw.optInt("calcium_pdv")
    var ironPDV: Int = raw.optInt("iron_pdv")
    var potassiumPDV: Int = raw.optInt("potassium_pdv")
    var itemId = raw.getInt("item_id")
}